NAME=perl-Data-Validate-Domain
VERSION=0.0
BUILDROOT=$(CURDIR)/$(NAME).buildroot
TARNAME = Data-Validate-Domain
TARVERSION = 0.09
TARBALL_POSTFIX = tar.gz
SOURCES = $(TARNAME)-$(TARVERSION).$(TARBALL_POSTFIX)
