NAME=perl-Data-Validate-IP
VERSION=0.0
BUILDROOT=$(CURDIR)/$(NAME).buildroot
TARNAME = Data-Validate-IP
TARVERSION = 0.11
TARBALL_POSTFIX = tar.gz
SOURCES = $(TARNAME)-$(TARVERSION).$(TARBALL_POSTFIX)
