NAME=perl-Net-Ping-External
VERSION=0.0
BUILDROOT=$(CURDIR)/$(NAME).buildroot
TARNAME = Net-Ping-External
TARVERSION = 0.12
TARBALL_POSTFIX = tar.gz
SOURCES = $(TARNAME)-$(TARVERSION).$(TARBALL_POSTFIX)
